"""Build both workshop decks from one narrative and executable code excerpts."""

from __future__ import annotations

import argparse
import ast
import hashlib
from html import escape
import io
import json
from pathlib import Path
import re
import tempfile
import textwrap
from xml.dom import minidom
from zipfile import ZipFile


ROOT = Path(__file__).resolve().parents[1]
CONTENT = ROOT / "docs/deck.json"
HTML = ROOT / "docs/index.html"
PPTX = ROOT / "GitHub-Copilot-SDK.pptx"
BEGIN = "<!-- BEGIN GENERATED SLIDES -->"
END = "<!-- END GENERATED SLIDES -->"
SECTIONS = (
    "1. SDK in detail",
    "2. SDK vs. CLI",
    "3. Capabilities",
    "4. Samples",
)
COLORS = ("58A6FF", "BC8CFF", "3FB950", "F78166")


def read_deck() -> dict:
    deck = json.loads(CONTENT.read_text(encoding="utf-8"))
    slides = deck["slides"]
    ids = [slide["id"] for slide in slides]
    if len(ids) != len(set(ids)):
        raise ValueError("Slide IDs must be unique.")
    samples = [slide["sample"] for slide in slides if "sample" in slide]
    if samples != [f"{i:02d}" for i in range(1, 9)]:
        raise ValueError("The deck must contain one detail slide per sample, in order.")
    seen_appendix = False
    sections = []
    for slide in slides:
        if slide.get("optional"):
            seen_appendix = True
        elif seen_appendix:
            raise ValueError("Optional appendix slides must follow the introduction.")
        section = slide["section"]
        if section in SECTIONS and (not sections or section != sections[-1]):
            sections.append(section)
    if sections != list(SECTIONS):
        raise ValueError("The four introduction chapters must remain contiguous.")
    return deck


def source_path(value: str) -> Path:
    root = ROOT.resolve()
    path = (root / value).resolve()
    if not path.is_relative_to(root) or not path.is_file():
        raise ValueError(f"Code excerpt is not a repository file: {value}")
    return path


def code_excerpt(spec: dict) -> str:
    if "text" in spec:
        return spec["text"].rstrip()
    path = source_path(spec["source"])
    source = path.read_text(encoding="utf-8")
    lines = source.splitlines()
    names = spec.get("symbols", [spec["symbol"]] if "symbol" in spec else [])
    if names:
        nodes = {
            node.name: node
            for node in ast.parse(source).body
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
        }
        excerpts = []
        for name in names:
            if name not in nodes:
                raise ValueError(f"{path.name}: no top-level symbol {name!r}")
            node = nodes[name]
            start = min([node.lineno] + [d.lineno for d in node.decorator_list])
            excerpts.append(textwrap.dedent("\n".join(lines[start - 1:node.end_lineno])))
        return "\n\n".join(excerpts)
    starts = [i for i, line in enumerate(lines) if line.lstrip().startswith(spec["start"])]
    if len(starts) != 1:
        raise ValueError(f"{path.name}: excerpt start must match once: {spec['start']!r}")
    start = starts[0]
    ends = [i for i in range(start, len(lines)) if lines[i].strip() == spec["end"].strip()]
    if not ends:
        raise ValueError(f"{path.name}: excerpt end not found: {spec['end']!r}")
    return textwrap.dedent("\n".join(lines[start:ends[0] + 1]))


def content_hash(deck: dict) -> str:
    source = json.dumps(deck, sort_keys=True, ensure_ascii=False)
    excerpts = "\n".join(
        code_excerpt(slide["code"]) for slide in deck["slides"] if "code" in slide
    )
    builder = Path(__file__).read_text(encoding="utf-8")
    dependencies = (ROOT / "scripts/requirements-slides.txt").read_text(encoding="utf-8")
    fingerprint = "\n".join((source, excerpts, builder, dependencies))
    return hashlib.sha256(fingerprint.encode("utf-8")).hexdigest()


def check_powerpoint(deck: dict) -> None:
    with ZipFile(PPTX) as package:
        properties = minidom.parseString(package.read("docProps/core.xml"))
        descriptions = properties.getElementsByTagName("dc:description")
        expected = f"Generated by scripts/build_slides.py; content-sha256={content_hash(deck)}"
        actual = "".join(
            child.data for node in descriptions for child in node.childNodes
            if child.nodeType == child.TEXT_NODE
        )
        if actual != expected:
            raise ValueError("PowerPoint is stale. Run python scripts/build_slides.py.")
        presentation = minidom.parseString(package.read("ppt/presentation.xml"))
        if len(presentation.getElementsByTagName("p:sldId")) != len(deck["slides"]):
            raise ValueError("PowerPoint slide count differs from docs/deck.json.")


def inline(text: str) -> str:
    return re.sub(r"`([^`]+)`", r"<code>\1</code>", escape(text))


def items_html(items: list[str]) -> str:
    return '<ul class="content-list">' + "".join(f"<li>{inline(item)}</li>" for item in items) + "</ul>"


def slide_source(slide: dict, deck: dict) -> str:
    if "sample" in slide:
        matches = list((ROOT / "examples").glob(f'{slide["sample"]}_*.py'))
        if len(matches) != 1:
            raise ValueError(f'{slide["id"]}: expected exactly one runnable sample.')
        path = matches[0].relative_to(ROOT).as_posix()
        return f'{deck["repository"]}/blob/main/{path}'
    return slide.get("source", deck["repository"])


def body_html(slide: dict, deck: dict, qr: str) -> str:
    layout = slide["layout"]
    if layout == "title":
        return (
            '<div class="title-grid"><h1 class="title-h1">'
            'GitHub Copilot<br><span class="accent">SDK</span></h1>'
            f'<aside class="title-qr" aria-label="Workshop repository">{qr}'
            f'<a class="qr-caption" href="{escape(deck["repository"])}">'
            'github.com/jeffrey-groneberg/ghcp_sdk</a></aside></div>'
        )
    heading = f'<h2>{inline(slide["title"])}</h2>'
    lead = f'<p class="intro-lead">{inline(slide["lead"])}</p>' if slide.get("lead") else ""
    if layout == "cards":
        cards = "".join(
            f'<div class="card"><h3>{inline(card["title"])}</h3><p>{inline(card["text"])}</p></div>'
            for card in slide["cards"]
        )
        body = f'<div class="intro-cards">{cards}</div>'
    elif layout == "columns":
        columns = "".join(
            f'<div><h3>{inline(column["title"])}</h3>{items_html(column["items"])}</div>'
            for column in slide["columns"]
        )
        body = f'<div class="intro-columns">{columns}</div>'
    elif layout == "table":
        headers = "".join(f'<th scope="col">{inline(cell)}</th>' for cell in slide["headers"])
        rows = "".join(
            "<tr>" + "".join(f"<td>{inline(cell)}</td>" for cell in row) + "</tr>"
            for row in slide["rows"]
        )
        body = f'<table class="intro-table"><thead><tr>{headers}</tr></thead><tbody>{rows}</tbody></table>'
    elif layout == "code":
        spec = slide["code"]
        text = code_excerpt(spec)
        source_attr = f' data-source="{escape(spec["source"])}"' if "source" in spec else ""
        source_label = inline(spec["label"])
        if "source" in spec:
            source_label = (
                f'<a href="{escape(deck["repository"])}/blob/main/{escape(spec["source"])}">'
                f'{source_label}</a>'
            )
        body = (
            f'<div class="intro-code">{items_html(slide["items"])}'
            f'<div class="code-window"><div class="titlebar">{source_label}</div>'
            f'<pre{source_attr}><code>{escape(text)}</code></pre></div></div>'
        )
    elif layout == "traces":
        traces = "".join(
            f'<div class="trace"><h3>{inline(trace["title"])}</h3>'
            f'<pre><code>{escape(trace["text"])}</code></pre></div>'
            for trace in slide["traces"]
        )
        body = f'<div class="intro-traces">{traces}</div>'
    elif layout == "references":
        links = "".join(
            f'<li><a href="{escape(link["url"])}">{inline(link["title"])}</a></li>'
            for link in slide["links"]
        )
        body = f'<div class="intro-columns">{items_html(slide["items"])}<ul class="content-list">{links}</ul></div>'
    else:
        raise ValueError(f"Unsupported slide layout: {layout}")
    note = f'<p class="intro-note">{inline(slide["note"])}</p>' if slide.get("note") else ""
    appendix = (
        '<button class="btn ghost appendix-toggle" type="button" aria-expanded="false">'
        "Show optional appendix (4 slides)</button>"
        if slide.get("appendix_entry") else ""
    )
    return heading + lead + body + note + appendix


def render_html(deck: dict, original: str) -> str:
    qr_match = re.search(r'<svg\b[^>]*shape-rendering="crispEdges".*?</svg>', original, re.S)
    if qr_match is None:
        raise ValueError("The existing repository QR asset is missing.")
    qr = qr_match.group(0)
    core_count = sum(not slide.get("optional", False) for slide in deck["slides"])
    appendix_count = len(deck["slides"]) - core_count
    sections = []
    for number, slide in enumerate(deck["slides"], 1):
        optional = slide.get("optional", False)
        classes = "slide intro-slide" + (" title-slide" if slide["layout"] == "title" else "")
        hidden = ' data-optional="true" hidden' if optional else ""
        title = escape(slide["title"], quote=True)
        header = ""
        if slide["layout"] != "title":
            header = (
                f'<div class="tab-strip"><span class="path">{escape(slide["section"])}</span>'
                f'<span class="meta">SDK {deck["sdk_version"]} · runtime {deck["runtime_version"]}</span></div>'
            )
        if optional:
            counter = f"A{number - core_count} / {appendix_count}"
        else:
            counter = f"{number:02d} / {core_count}"
        source = slide_source(slide, deck)
        footer = (
            '<div class="slide-footer">'
            f'<span class="crumb">{escape(slide["section"])}</span>'
            f'<a class="src" href="{escape(source)}" target="_blank" rel="noopener">Source</a>'
            f'<span>{counter}</span></div>'
        )
        sections.append(
            f'<section id="{slide["id"]}" class="{classes}" aria-label="{title}"{hidden}>\n'
            + header + '\n<div class="slide-content">\n'
            + body_html(slide, deck, qr) + "\n</div>\n" + footer + "\n</section>"
        )
    generated = BEGIN + "\n" + "\n\n".join(sections) + "\n" + END
    if BEGIN in original and END in original:
        start = original.index(BEGIN)
        end = original.index(END, start) + len(END)
    else:
        start = original.index('<section class="slide')
        end = original.rindex("</section>") + len("</section>")
    result = original[:start] + generated + original[end:]
    return re.sub(r"<title>.*?</title>", f"<title>{escape(deck['title'])}</title>", result, count=1)


def render_pptx(deck: dict, destination: Path) -> None:
    from lxml import etree
    from pptx import Presentation
    from pptx.dml.color import RGBColor
    from pptx.enum.shapes import MSO_AUTO_SHAPE_TYPE
    from pptx.opc.constants import RELATIONSHIP_TYPE as RT
    from pptx.oxml import parse_xml
    from pptx.util import Inches, Pt
    import qrcode

    presentation = Presentation()
    presentation.slide_width = Inches(13.333333)
    presentation.slide_height = Inches(7.5)
    presentation.core_properties.title = deck["title"]
    presentation.core_properties.subject = "Repository assistant: SDK 1.0.13 / runtime 1.0.83"
    presentation.core_properties.author = "Jeffrey Groneberg"
    presentation.core_properties.comments = (
        f"Generated by scripts/build_slides.py; content-sha256={content_hash(deck)}"
    )
    # PowerPoint uses theme hyperlink colors even when text runs specify RGB.
    theme_part = presentation.part.part_related_by(RT.THEME)
    theme = parse_xml(theme_part.blob)
    for kind in ("hlink", "folHlink"):
        color = theme.xpath(f"./a:themeElements/a:clrScheme/a:{kind}/*")[0]
        color.set("val", "58A6FF")
    theme_part._blob = etree.tostring(theme, xml_declaration=True, encoding="UTF-8", standalone=True)
    fg, muted, background = "E6EDF3", "9DA7B3", "0D1117"
    width = 12.1
    core_count = sum(not slide.get("optional", False) for slide in deck["slides"])
    appendix_count = len(deck["slides"]) - core_count

    def box(slide, x, y, w, h, fill="161B22"):
        shape = slide.shapes.add_shape(
            MSO_AUTO_SHAPE_TYPE.ROUNDED_RECTANGLE,
            Inches(x), Inches(y), Inches(w), Inches(h),
        )
        shape.fill.solid()
        shape.fill.fore_color.rgb = RGBColor.from_string(fill)
        shape.line.color.rgb = RGBColor.from_string("30363D")
        return shape

    def text(slide, value, x, y, w, h, size=18, color=fg, bold=False, mono=False):
        shape = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
        frame = shape.text_frame
        frame.word_wrap = not mono
        frame.margin_left = frame.margin_right = 0
        frame.margin_top = frame.margin_bottom = 0
        for index, line in enumerate(value.split("\n")):
            paragraph = frame.paragraphs[0] if index == 0 else frame.add_paragraph()
            paragraph.text = line if mono else line.replace("`", "")
            paragraph.space_before = paragraph.space_after = Pt(0)
            paragraph.line_spacing = 1.16
            paragraph.font.name = "Courier New" if mono else "Calibri"
            paragraph.font.size = Pt(size)
            paragraph.font.bold = bold
            paragraph.font.color.rgb = RGBColor.from_string(color)
        return shape

    def items(slide, values, x, y, w, h, size=17):
        shape = text(slide, "\n\n".join(values), x, y, w, h, size=size)
        return shape

    def note(slide, value):
        text(slide, value, 0.6, 6.34, width, 0.53, size=11.5, color=muted)

    for number, data in enumerate(deck["slides"], 1):
        slide = presentation.slides.add_slide(presentation.slide_layouts[6])
        slide.background.fill.solid()
        slide.background.fill.fore_color.rgb = RGBColor.from_string(background)
        optional = data.get("optional", False)
        if optional:
            slide._element.set("show", "0")
        counter = (
            f"A{number - core_count} / {appendix_count}"
            if optional else f"{number:02d} / {core_count}"
        )
        if data["layout"] != "title":
            text(slide, data["section"], 0.6, 0.3, 7.3, 0.25, size=11, color=muted)
        text(slide, counter, 11.65, 7.02, 1.05, 0.23, size=10, color=muted)
        source = slide_source(data, deck)
        source_box = text(slide, "Source", 0.6, 7.02, 9.8, 0.23, size=10, color=COLORS[0])
        source_box.text_frame.paragraphs[0].runs[0].hyperlink.address = source
        source_box.text_frame.paragraphs[0].runs[0].font.underline = True
        layout = data["layout"]
        if layout == "title":
            text(slide, "GitHub Copilot\nSDK", 0.8, 2.13, 8.4, 2.0, size=49, bold=True)
            image = io.BytesIO()
            qrcode.make(deck["repository"]).save(image, format="PNG")
            image.seek(0)
            slide.shapes.add_picture(image, Inches(10.0), Inches(2.45), width=Inches(2.35))
            continue
        text(slide, data["title"], 0.6, 0.78, width, 0.89, size=30, bold=True)
        y = 1.88
        if data.get("lead"):
            text(slide, data["lead"], 0.6, 1.65, width, 0.58, size=16, color=muted)
            y = 2.35
        height = 6.12 - y
        if layout == "cards":
            count = len(data["cards"])
            columns = 2 if count == 4 else count
            rows = 2 if count == 4 else 1
            gap = 0.3
            card_width = (width - gap * (columns - 1)) / columns
            card_height = (height - gap * (rows - 1)) / rows
            for index, card in enumerate(data["cards"]):
                x = 0.6 + (index % columns) * (card_width + gap)
                cy = y + (index // columns) * (card_height + gap)
                box(slide, x, cy, card_width, card_height)
                text(slide, card["title"], x + 0.23, cy + 0.22, card_width - 0.46, 0.55, size=21, bold=True)
                text(slide, card["text"], x + 0.23, cy + 0.91, card_width - 0.46, card_height - 1.08, size=17, color=muted)
        elif layout in ("columns", "references"):
            columns = data.get("columns", [
                {"title": "Workshop", "items": data.get("items", [])},
                {"title": "References", "items": [link["title"] for link in data.get("links", [])]},
            ])
            for index, column in enumerate(columns):
                x = 0.6 + index * 6.25
                text(slide, column["title"], x, y, 5.85, 0.5, size=22, bold=True, color=COLORS[index])
                shape = items(slide, column["items"], x, y + 0.73, 5.7, height - 0.8)
                if layout == "references" and index == 1:
                    paragraphs = [p for p in shape.text_frame.paragraphs if p.text]
                    for paragraph, link in zip(paragraphs, data["links"], strict=True):
                        paragraph.runs[0].hyperlink.address = link["url"]
                        paragraph.runs[0].font.underline = True
            if data.get("appendix_entry"):
                note(slide, "Introduction complete. Optional appendix: runtime deployment, multi-user hosting, authentication, and BYOK.")
        elif layout == "table":
            rows, cols = len(data["rows"]) + 1, len(data["headers"])
            table_height = height - (0.22 if data["id"] == "appendix-auth" else 0)
            shape = slide.shapes.add_table(rows, cols, Inches(0.6), Inches(y), Inches(width), Inches(table_height))
            table = shape.table
            if data["id"] == "appendix-auth":
                table.rows[0].height = Inches(0.42)
                for row in list(table.rows)[1:]:
                    row.height = Inches((table_height - 0.42) / (rows - 1))
            fractions = [0.085, 0.235, 0.68] if data["id"] == "agent-turn" else (
                [0.11, 0.25, 0.64] if data["id"] == "checkpoint-map" else (
                    [0.22, 0.39, 0.39] if cols == 3 else [0.28, 0.72]
                )
            )
            for col, fraction in zip(table.columns, fractions, strict=True):
                col.width = Inches(width * fraction)
            for r, values in enumerate([data["headers"]] + data["rows"]):
                for c, value in enumerate(values):
                    cell = table.cell(r, c)
                    cell.fill.solid()
                    cell.fill.fore_color.rgb = RGBColor.from_string("161B22" if r % 2 == 0 else background)
                    cell.margin_left = cell.margin_right = Inches(0.12)
                    cell.margin_top = cell.margin_bottom = Inches(
                        0.06 if data["id"] == "appendix-auth" else 0.09
                    )
                    cell.text = value.replace("`", "")
                    paragraph = cell.text_frame.paragraphs[0]
                    paragraph.font.name = "Calibri"
                    paragraph.font.size = Pt(15 if rows >= 8 else 17)
                    paragraph.font.bold = r == 0
                    paragraph.font.color.rgb = RGBColor.from_string(COLORS[0] if r == 0 else fg)
                    paragraph.line_spacing = 1.08
        elif layout == "code":
            items(slide, data["items"], 0.6, y, 3.3, height, size=16.5)
            spec = data["code"]
            excerpt = code_excerpt(spec)
            code_x, code_width = 4.25, 8.45
            box(slide, code_x, y, code_width, height, fill="010409")
            text(slide, spec["label"], code_x + 0.2, y + 0.15, code_width - 0.4, 0.4, size=10.5, color=muted)
            lines = excerpt.splitlines()
            if len(lines) > 23 or max(map(len, lines), default=0) > 88:
                raise ValueError(f'{data["id"]}: shorten the source excerpt; it exceeds the code panel budget.')
            text(slide, excerpt, code_x + 0.2, y + 0.7, code_width - 0.4, height - 0.85, size=11.5, mono=True)
        elif layout == "traces":
            for index, trace in enumerate(data["traces"]):
                x = 0.6 + index * 6.25
                box(slide, x, y, 5.85, height, fill="010409")
                text(slide, trace["title"], x + 0.25, y + 0.25, 5.35, 0.5, size=22, bold=True, color=COLORS[3 if index == 0 else 2])
                text(slide, trace["text"], x + 0.25, y + 1.1, 5.35, height - 1.3, size=13.5, mono=True)
        else:
            raise ValueError(f"Unsupported PowerPoint layout: {layout}")
        if data.get("note"):
            note(slide, data["note"])
        slide.notes_slide.notes_text_frame.text = (
            f"{data['title']}\nSource: {source}\n"
            + ("Optional appendix slide. " if optional else "")
            + data.get("note", "")
        )
    with tempfile.TemporaryDirectory(prefix=".slides-", dir=destination.parent) as temp:
        output = Path(temp) / destination.name
        presentation.save(output)
        output.replace(destination)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated HTML is stale.")
    parser.add_argument("--html-only", action="store_true", help="Skip PowerPoint generation.")
    args = parser.parse_args()
    deck = read_deck()
    original = HTML.read_text(encoding="utf-8")
    rendered = render_html(deck, original)
    if args.check:
        if rendered != original:
            raise SystemExit("Slides are stale. Run python scripts/build_slides.py.")
        check_powerpoint(deck)
        print(f"Both decks and executable excerpts match the {len(deck['slides'])}-slide source.")
        return
    if not args.html_only:
        render_pptx(deck, PPTX)
    HTML.write_text(rendered, encoding="utf-8")
    print(f"Built {len(deck['slides'])} slides from docs/deck.json.")


if __name__ == "__main__":
    main()
